[functions]
directory = "netlify/functions"

[[redirects]]
from = "/auth/discord"
to = "/.netlify/functions/auth-discord"
status = 200

[[redirects]]
from = "/auth/callback"
to = "/.netlify/functions/auth-callback"
status = 200
